// Sidequest wireframe · screen registry.
// One list drives the sidebar site map (index.html), the static board (board.html) and the product map (sitemap.html).
// Each screen: id (used in links: index.html#id), fig (Figma frame number, or '' if it came from Kimmy's prototype only),
// title, go() puts the app in that state, is(w) recognises it, note is the board annotation.
'use strict';
(() => {
  const X = window.Sidequest;
  const A = (tab) => () => X.base('attendee', tab);
  const H = (tab) => () => X.base('host', tab);
  const onb = (flow, i, setup) => () => X.onboarding(flow, i, setup);
  const O_ = (flow, step) => (w) => w.onb === `${flow}:${step}`;
  const page = (v, extra) => (w) => w.page === v && (!extra || extra(w));
  const tabIs = (mode, tab, extra) => (w) => w.mode === mode && w.tab === tab && !w.page && (!extra || extra(w));

  // [group id, group title, side, screens[]]
  const GROUPS = [
    ['start', 'Onboarding · shared', 'Attendee', [
      { id: 'welcome', fig: '01', title: 'Landing', go: onb('start', 0), is: O_('start', 'welcome'),
        note: 'Slide to start. "Already have an account? Log in" replaces the old sign-in wording.' },
      { id: 'role', fig: '', title: 'Going out or hosting', go: onb('start', 1), is: O_('start', 'role'),
        note: 'One login for both sides. You can switch between accounts later, like Instagram.' },
    ]],
    ['onb', 'Onboarding · attendee', 'Attendee', [
      { id: 'signup', fig: '02', title: 'Sign up', go: onb('attendee', 0), is: O_('attendee', 'signup'),
        note: 'Name, username, email, phone and password, or Apple / Google. Username is new: friends find you by it.' },
      { id: 'meet-sixer', fig: '', title: 'Meet Sixer', go: onb('attendee', 1), is: O_('attendee', 'sixer'),
        note: 'Sixer is the taste avatar and AI guide. It always says why it picked something.' },
      { id: 'vibes', fig: '03', title: 'Vibes', go: onb('attendee', 2), is: O_('attendee', 'scenes'),
        note: 'Top 10 most picked vibes as tiles, then a searchable list of more. Pick two or more.' },
      { id: 'past-events', fig: '04', title: 'Quests you\'ve been to', go: onb('attendee', 3), is: O_('attendee', 'past'),
        note: 'Past events seed taste. Upcoming tickets import from DICE or Ticketmaster. Eventbrite blocks imports, so it offers a screenshot instead.' },
      { id: 'times', fig: '06', title: 'When you go out', go: onb('attendee', 4), is: O_('attendee', 'times'),
        note: 'Day or night plus weekday or weekend, split out of the old Location screen.' },
      { id: 'areas', fig: '06', title: 'Areas you frequent', go: onb('attendee', 5), is: O_('attendee', 'areas'),
        note: 'Reworded to "Which areas do you frequent?" The "how do you get around" question is gone.' },
      { id: 'party-invite', fig: '05', title: 'Assemble your party', go: onb('attendee', 6), is: O_('attendee', 'crew'),
        note: 'Import contacts, or find people by email, phone or username. Nobody is messaged without you.' },
      { id: 'taste-ready', fig: '07', title: 'Taste avatar ready', go: onb('attendee', 7), is: O_('attendee', 'build'),
        note: 'Builds Weekly Quests. No extra check step: tags can be edited later in Profile.' },
    ]],
    ['discover', 'Discover', 'Attendee', [
      { id: 'discover', fig: '08', title: 'Discover · list', go: A('discover'), is: tabIs('attendee', 'discover', (w) => !w.filters && !w.empty && w.dayPart === 'any'),
        note: 'Weekly Quests, Vibe Mixes and a request card. List or Map toggle, quick filters for price, distance, friends and vibe. Bell opens notifications.' },
      { id: 'map', fig: '09', title: 'Discover · map', go: A('map'), is: tabIs('attendee', 'map', (w) => !w.mapSel),
        note: 'Pins are toned by match tier (darkest is the best match), with a legend. No percentages.' },
      { id: 'map-pin', fig: '10', title: 'Map · pin selected', go: () => { A('map')(); X.mut((S) => { S.mapSel = 'vinyl'; }); }, is: tabIs('attendee', 'map', (w) => !!w.mapSel),
        note: 'Tapping a pin shows its card. "Send to party" was removed here; Share now lives on the quest page.' },
      { id: 'filters', fig: '11', title: 'Filters', go: () => { A('discover')(); X.fire('filters'); }, is: page('filters'),
        note: 'Price, distance, friends going, vibe, start time and amenities (step-free, all ages, food, drinks, small crowd).' },
      { id: 'no-matches', fig: '12', title: 'No matches', go: () => { A('discover')(); X.mut((S) => { Object.assign(S.filters, { price: 'free', dist: 'walk', vibe: 'film' }); }); }, is: tabIs('attendee', 'discover', (w) => w.empty),
        note: 'Clear filters, or turn the search into a quest request.' },
      { id: 'notifications', fig: '15', title: 'Notifications', go: () => { A('discover')(); X.fire('notifs'); }, is: page('notifs'),
        note: 'Quest changes, friends inviting you, friend requests (accept in place) and "you asked, it\'s happening".' },
      { id: 'weekly', fig: '', title: 'Weekly Quests · full list', go: () => { A('discover')(); X.push('mix', { id: 'weekly' }); }, is: page('mix', (w) => w.id === 'weekly'),
        note: 'This week\'s picks, refreshed every Monday.' },
      { id: 'vibe-mix', fig: '', title: 'Vibe Mix', go: () => { A('discover')(); X.push('mix', { id: 'live' }); }, is: page('mix', (w) => w.id !== 'weekly'),
        note: 'One vibe, ranked by match.' },
    ]],
    ['quest', 'Quest & tickets', 'Attendee', [
      { id: 'quest', fig: '13', title: 'Quest detail', go: () => { A('discover')(); X.push('event', { id: 'vinyl' }); }, is: page('event', (w) => w.id !== 'rooftop' && w.id !== 'disco'),
        note: 'Bookmark and share at the top. Start and end time, ratings (quest if recurring, host, venue), who\'s going and special guests, payments, amenities, how to get here. The ticket button links to the platform.' },
      { id: 'quest-19', fig: '', title: 'Quest detail · 19+', go: () => { A('discover')(); X.push('event', { id: 'rooftop' }); }, is: page('event', (w) => w.id === 'rooftop' || w.id === 'disco'),
        note: 'Same layout, with the 19+ badge.' },
      { id: 'tickets', fig: '14', title: 'Tickets', go: () => { A('discover')(); X.push('event', { id: 'vinyl' }); X.push('tickets', { id: 'vinyl' }); }, is: page('tickets'),
        note: 'Hands off to the host\'s ticket page. "I have my ticket" leads to Import ticket.' },
      { id: 'import-ticket', fig: '14', title: 'Import ticket', go: () => { A('discover')(); X.push('event', { id: 'vinyl' }); X.push('import', { id: 'vinyl' }); }, is: page('import'),
        note: 'Scan a QR, upload a screenshot, or connect DICE or Ticketmaster.' },
      { id: 'wallet', fig: 'New', title: 'Ticket wallet', go: () => { A('log')(); X.fire('wallet'); }, is: page('wallet'),
        note: 'New screen from team notes: every quest you plan to attend, with the ticket ready to scan.' },
      { id: 'age-check', fig: '', title: '19+ check', go: () => { X.set('age', null); A('discover')(); X.push('event', { id: 'rooftop' }); X.fire('tickets', { id: 'rooftop' }); }, is: page('agecheck'),
        note: 'Only asked for 19+ quests, then remembered.' },
      { id: 'all-ages', fig: '', title: 'All-ages alternatives', go: () => { A('discover')(); X.push('allages', { id: 'rooftop' }); }, is: page('allages'),
        note: 'If you\'re under 19, you get similar all-ages quests instead of a dead end.' },
    ]],
    ['parties', 'Parties', 'Attendee', [
      { id: 'parties', fig: '16', title: 'Parties', go: A('parties'), is: tabIs('attendee', 'parties'),
        note: 'Your friend groups. A group page, not the main selling point.' },
      { id: 'party', fig: '17', title: 'Party · Crew Blend', go: () => { A('parties')(); X.fire('party', { id: 'friday' }); }, is: page('party', (w) => w.id === 'friday'),
        note: 'Shared themes from everyone\'s taste, group picks, and a vote. Voters show as faces, not percentages. "Pending" and "group pick" replace "in-vote" and "blended pick".' },
      { id: 'party-big', fig: '17', title: 'Party · 6+ people', go: () => { A('parties')(); X.fire('party', { id: 'brunch' }); }, is: page('party', (w) => w.id === 'brunch'),
        note: 'Parties bigger than 5 get a podium of the top 3 picks, so ties stay readable.' },
      { id: 'group-plan', fig: '', title: 'Group plan', go: () => { A('parties')(); X.fire('plan', { id: 'vinyl' }); }, is: page('plan'),
        note: 'Everyone replies in or out. The plan locks when the party is in.' },
    ]],
    ['requests', 'Quest Requests', 'Attendee', [
      { id: 'requests', fig: '18', title: 'Quest Requests', go: A('requests'), is: tabIs('attendee', 'requests'),
        note: 'What people want that isn\'t on yet. "Me too" counts you once; each account counts once.' },
      { id: 'request-new', fig: '19', title: 'Request a quest', go: () => { A('requests')(); X.fire('signal'); }, is: page('signal'),
        note: 'No "who\'s coming" field. Friends back it from their own accounts, which hosts trust more. Similar requests show first.' },
    ]],
    ['log', 'Quest Log', 'Attendee', [
      { id: 'quest-log', fig: '20', title: 'Quest Log · upcoming', go: A('log'), is: tabIs('attendee', 'log', (w) => w.seg === 'upcoming' && w.logView === 'list'),
        note: 'Upcoming, Bookmarked and Past quests. List or calendar, plus the ticket wallet.' },
      { id: 'quest-log-cal', fig: '20', title: 'Quest Log · calendar', go: () => { A('log')(); X.fire('log-view'); }, is: tabIs('attendee', 'log', (w) => w.seg === 'upcoming' && w.logView === 'calendar'),
        note: 'Calendar view, from the Partiful reference.' },
      { id: 'bookmarked', fig: '20', title: 'Quest Log · bookmarked', go: () => { A('log')(); X.fire('seg', { v: 'saved' }); }, is: tabIs('attendee', 'log', (w) => w.seg === 'saved'),
        note: 'Everything you bookmarked, with no plan or ticket yet.' },
      { id: 'past-quests', fig: '20', title: 'Quest Log · past quests', go: () => { A('log')(); X.fire('seg', { v: 'past' }); }, is: tabIs('attendee', 'log', (w) => w.seg === 'past'),
        note: 'Your quest memory book. Unrated quests are flagged.' },
      { id: 'event-day', fig: '21', title: 'Event day mode', go: () => { A('log')(); X.push('hub', { id: 'listening' }); }, is: page('hub'),
        note: 'All event details in one box: doors, entrance, floor plan from the host, your route home, live updates.' },
      { id: 'attendee-chat', fig: '22', title: 'Attendee chat', go: () => { A('log')(); X.push('hub', { id: 'listening' }); X.fire('room', { id: 'listening' }); }, is: page('room'),
        note: 'Pinned host posts and threads the host sets up (like Discord forums). Profile icons, not names.' },
      { id: 'check-in', fig: '', title: 'Check-in · scan', go: () => { A('log')(); X.push('hub', { id: 'listening' }); X.push('checkin', { id: 'listening' }); }, is: page('checkin', (w) => !w.done),
        note: 'Scan the door QR to check in.' },
      { id: 'checked-in', fig: '', title: 'Check-in · done', go: () => { A('log')(); X.push('hub', { id: 'listening' }); X.push('checkin', { id: 'listening' }); X.fire('checkin-done', { id: 'listening' }); }, is: page('checkin', (w) => w.done),
        note: 'Check-ins teach Sixer what you actually go to.' },
      { id: 'rate', fig: '23', title: 'Rate your quest', go: () => { A('log')(); X.fire('seg', { v: 'past' }); X.push('recap', { id: 'harbour' }); }, is: page('recap'),
        note: 'Overall stars, then optional categories like Google Maps: host, ambience, venue, accessibility, vibes. "Save to past quests" replaces "Collect this story".' },
      { id: 'saved-quest', fig: '', title: 'Saved quest', go: () => { A('log')(); X.fire('seg', { v: 'past' }); X.push('night', { id: 'ramen' }); }, is: page('night'),
        note: 'The saved memory: ratings, photos, who you were with.' },
      { id: 'wrapped', fig: '', title: 'Sidequest Wrapped', go: () => { A('log')(); X.fire('seg', { v: 'past' }); X.push('wrapped', { i: 0 }); }, is: page('wrapped'),
        note: 'Your year in quests.' },
    ]],
    ['sixer', 'Sixer', 'Attendee', [
      { id: 'sixer', fig: '', title: 'Ask Sixer', go: () => { A('discover')(); X.chat(); }, is: (w) => w.chat,
        note: 'The AI guide in the middle of the tab bar. Answers with real quests and explains each pick by match tier, distance, time and friends.' },
    ]],
    ['profile', 'Profile', 'Attendee', [
      { id: 'profile', fig: '24', title: 'Profile', go: () => { A('discover')(); X.push('profile'); }, is: page('profile', (w) => !w.edit),
        note: 'Read-only until you tap Edit, so nothing changes by accident. Shows what Sixer knows.' },
      { id: 'profile-edit', fig: '24', title: 'Profile · editing', go: () => { A('discover')(); X.push('profile'); X.fire('edit-profile'); }, is: page('profile', (w) => w.edit),
        note: 'Edit name, username, photo, vibes, times and areas.' },
      { id: 'accounts', fig: '24', title: 'Switch account', go: () => { A('discover')(); X.push('profile'); X.push('accounts'); }, is: page('accounts'),
        note: 'Quick switch between your personal and host accounts.' },
    ]],
    ['honb', 'Onboarding · host', 'Host', [
      { id: 'host-type', fig: '25', title: 'Host type', go: onb('host', 0), is: O_('host', 'htype'),
        note: 'Adds independent hosts and artists / collectives, plus "Other" with a text box.' },
      { id: 'host-account', fig: '26', title: 'Host account', go: onb('host', 1), is: O_('host', 'haccount'),
        note: 'Host name, work email and work phone.' },
      { id: 'host-verify', fig: '28', title: 'Verification', go: onb('host', 2), is: O_('host', 'verify'),
        note: 'Instagram business account, business number, or website.' },
      { id: 'host-profile-setup', fig: '27', title: 'Host profile', go: onb('host', 3), is: O_('host', 'hprofile'),
        note: 'Searchable vibe tags. "Add social" for any platform, all optional.' },
      { id: 'host-ticketing', fig: '29', title: 'Ticketing', go: onb('host', 4), is: O_('host', 'ticketing'),
        note: 'Connect DICE, Eventbrite or Ticketmaster so Insights can show sales and revenue. Own site or free RSVP gives views, taps and check-ins only.' },
      { id: 'host-team', fig: '30', title: 'Team', go: onb('host', 5), is: O_('host', 'team'),
        note: 'Owners and marketing only. Door staff are invited per quest.' },
      { id: 'host-claim', fig: '', title: 'Claim listings', go: onb('host', 6), is: O_('host', 'claim'),
        note: 'Claim quests already listed under your name.' },
      { id: 'host-review', fig: '31', title: 'Review', go: onb('host', 7), is: O_('host', 'review'),
        note: 'Submitted, in review, approved. Drafts can be set up while waiting.' },
      { id: 'host-ready', fig: '', title: 'Demand map ready', go: onb('host', 8), is: O_('host', 'hbuild'),
        note: 'Counts the people already asking for what you host.' },
    ]],
    ['host', 'Host', 'Host', [
      { id: 'h-demand', fig: '37', title: 'Demand insights', go: H('demand'), is: tabIs('host', 'demand'),
        note: 'Quest requests by vibe, area and night, with how many hosts are already planning each.' },
      { id: 'h-request', fig: '38', title: 'Request detail', go: () => { H('demand')(); X.push('idea', { id: 'i-ramen' }); }, is: page('idea'),
        note: 'Several hosts can claim the same request. Everyone sees who else is planning one.' },
      { id: 'h-draft', fig: '', title: 'Draft test', go: () => { H('demand')(); X.fire('idea', { id: 'i-ramen' }); X.fire('post-draft', { id: 'i-ramen' }); }, is: page('draft'),
        note: 'Test interest with a draft before booking a venue.' },
      { id: 'h-create', fig: '34', title: 'Create a quest', go: () => { H('demand')(); X.push('idea', { id: 'i-ramen' }); X.push('create', { id: 'i-ramen' }); }, is: page('create'),
        note: 'Prefilled from the request. Start and end time, searchable tags, payments, amenities, connected ticketing.' },
      { id: 'h-dayinfo', fig: '35', title: 'Event day info', go: () => { H('quests')(); X.push('dayinfo', { id: 'i-ramen' }); }, is: page('dayinfo'),
        note: 'Floor plan, entrances, accessibility. Routes there and home are generated per attendee, not typed by the host.' },
      { id: 'h-published', fig: '36', title: 'Quest published', go: () => { H('demand')(); X.push('create', { id: 'i-ramen' }); X.fire('cq-publish', { id: 'i-ramen' }); }, is: page('published'),
        note: 'Who gets told: people who requested it, matched attendees in Weekly Quests, followers.' },
      { id: 'h-quests', fig: '33', title: 'Your quests', go: H('quests'), is: tabIs('host', 'quests', (w) => w.qseg === 'live'),
        note: 'Drafts, Live and Past. Create a quest from here too.' },
      { id: 'h-drafts', fig: '33', title: 'Your quests · drafts', go: () => { H('quests')(); X.fire('hseg', { v: 'drafts' }); }, is: tabIs('host', 'quests', (w) => w.qseg === 'drafts'),
        note: 'Draft tests and duplicated quests.' },
      { id: 'h-past', fig: '33', title: 'Your quests · past', go: () => { H('quests')(); X.fire('hseg', { v: 'past' }); }, is: tabIs('host', 'quests', (w) => w.qseg === 'past'),
        note: 'Recap or duplicate a past quest.' },
      { id: 'h-eventday', fig: '41', title: 'Event day tools', go: () => { H('quests')(); X.push('hevent', { id: 'rooftop' }); }, is: page('hevent'),
        note: 'Headcount, guest list grouped by party, door QR, chat moderators, live updates.' },
      { id: 'h-recap', fig: '42', title: 'Recap', go: () => { H('quests')(); X.fire('hseg', { v: 'past' }); X.push('hrecap', { id: 'vinyl-last' }); }, is: page('hrecap'),
        note: 'How the last one went: matched guests, ratings by category, what to change.' },
      { id: 'h-insights', fig: '32', title: 'Insights', go: H('insights'), is: tabIs('host', 'insights', (w) => w.iseg === 'performance'),
        note: 'Filter by quest, venue and dates, like a Google Analytics tab. Average attendees, revenue and vendor revenue (from connected ticketing), views to purchase.' },
      { id: 'h-audience', fig: '39', title: 'Audience', go: () => { H('insights')(); X.fire('iseg', { v: 'audience' }); }, is: tabIs('host', 'insights', (w) => w.iseg === 'audience'),
        note: 'Who comes: vibes, areas, solo or in parties, returning guests.' },
      { id: 'h-inbox', fig: '40', title: 'Inbox', go: H('inbox'), is: tabIs('host', 'inbox'),
        note: 'Last-minute announcements to ticket holders or followers. Send now or schedule.' },
      { id: 'h-profile', fig: '', title: 'Host profile', go: () => { H('demand')(); X.fire('hprofile'); }, is: page('hprofile'),
        note: 'Public host page: vibes, socials, team, switch to personal account.' },
    ]],
  ];

  const flat = [];
  GROUPS.forEach(([gid, gtitle, side, list], gi) => list.forEach((s, si) => flat.push(Object.assign(s, { group: gid, groupTitle: gtitle, side, num: `${String(gi + 1).padStart(2, '0')}.${si + 1}` }))));
  window.SQ_SCREENS = { GROUPS, flat, byId: Object.fromEntries(flat.map((s) => [s.id, s])) };
})();
